concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "tarantella_runner"
  url = "https://gitlab.itwm.fraunhofer.de/"
  token = "bduDJVzUiSMsN8dUor8U"
  executor = "shell"
  pre_clone_script = "source /home/gitlab-runner/workspace/setup-env.sh"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
