.cache_key_forward:
  script:
    - echo "Using cache key ${CACHE_KEY-None}."
  artifacts:
    when: always
    expire_in: 1 day
    reports:
      dotenv: ${CI_PROJECT_DIR}/cache_key_${CI_JOB_ID}.env
  after_script:
    - echo "CACHE_KEY=${CACHE_KEY}" > ${CI_PROJECT_DIR}/cache_key_${CI_JOB_ID}.env

.cache_pull_job:
  extends:
    - .cache_key_forward
  cache:
    key: ${CACHE_KEY}
    paths:
      - ${CACHE_DIR}/${CACHE_KEY}
    policy: pull

.cache_setup_job:
  extends:
    - .cache_key_forward
  cache:
    key: ${CACHE_KEY}
    paths:
      - ${CACHE_DIR}/${CACHE_KEY}

.common_build_job:
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - ${TNT_BUILD_DIR}
  script:
    - echo TNT_BUILD_TYPE=${TNT_BUILD_TYPE}
    - echo TNT_TEST_MACHINEFILE=${TNT_TEST_MACHINEFILE}
    - rm -rf ${TNT_INSTALL_DIR}
    - rm -rf ${TNT_BUILD_DIR} && mkdir ${TNT_BUILD_DIR}
    - cd ${TNT_BUILD_DIR}
    - cmake -DTNT_TEST_MACHINEFILE=${TNT_TEST_MACHINEFILE} -DCMAKE_BUILD_TYPE=${TNT_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=${TNT_INSTALL_DIR} -DENABLE_TESTING=ON ${CI_PROJECT_DIR}
    - make -j$(nproc)

.release_job:
  variables:
    TNT_BUILD_TYPE: Release

.debug_job:
  variables:
    TNT_BUILD_TYPE: Debug

.eth_job:
  variables:
    TNT_NETWORK_TYPE: "eth"

.ib_job:
  variables:
    TNT_NETWORK_TYPE: "ib"
