.build_gaspicxx_job:
  extends:
    - .cache_setup_job
  script:
    - export GASPICXX_SHA1=${GASPICXX_SHA1-master}
    - if [[ ! -d ${CACHE_DIR}/${CACHE_KEY} ]];
      then
      if [ "`cat ${CI_PROJECT_DIR}/${CACHE_DIR}/${CACHE_KEY}/gaspicxx.lock`" != "${GASPICXX_SHA1}" ];
      then
        which gaspi_run;
        git clone git@gitlab.itwm.fraunhofer.de:gruenewa/GaspiCxx.git ${GASPICXX_DIR};
        cd ${GASPICXX_DIR};
        git checkout -b test_ci ${GASPICXX_SHA1};
        rm -rf build;
        mkdir -p build;
        cd build;
        cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=${GASPICXX_INSTALL_DIR} ../ ;
        make -j$(nproc) install;
        echo ${GASPICXX_SHA1} >> ${CI_PROJECT_DIR}/${CACHE_DIR}/${CACHE_KEY}/gaspicxx.lock;
      fi;
      fi
    - env | grep CACHE >> ${CI_PROJECT_DIR}/dep_build_${CI_JOB_ID}.env
    - echo "GASPICXX_INSTALL_DIR=${GASPICXX_INSTALL_DIR}" >> ${CI_PROJECT_DIR}/dep_build_${CI_JOB_ID}.env
    - echo "LD_LIBRARY_PATH=${GASPICXX_INSTALL_DIR}/lib:${LD_LIBRARY_PATH}" >> ${CI_PROJECT_DIR}/dep_build_${CI_JOB_ID}.env
    - echo "PYTHONPATH=${GASPICXX_INSTALL_DIR}/lib:${PYTHONPATH}" >> ${CI_PROJECT_DIR}/dep_build_${CI_JOB_ID}.env
    - echo "CMAKE_PREFIX_PATH=${GASPICXX_INSTALL_DIR}:${CMAKE_PREFIX_PATH}" >> ${CI_PROJECT_DIR}/dep_build_${CI_JOB_ID}.env
  artifacts:
    when: always
    expire_in: 1 day
    reports:
      dotenv: ${CI_PROJECT_DIR}/dep_build_${CI_JOB_ID}.env
