stages:
  - build
  - unit_tests_cpp
  - unit_tests_python
  - integration_tests
  - unit_tests_python_nightly
  - integration_tests_nightly

variables:
  GIT_STRATEGY: fetch
  TNT_CI_DIR: ${CI_PROJECT_DIR}/meta/ci
  TNT_INSTALL_DIR: ${CI_PROJECT_DIR}/install
  TNT_BUILD_DIR: ${CI_PROJECT_DIR}/build
  TNT_LD_LIBRARY_PATH: ${CI_PROJECT_DIR}/build
  RUNNER_HOME: /home/gitlab-runner

include: 
  - local: meta/ci/config/common.yml
  - local: meta/ci/config/tnt_cluster.yml
  - local: meta/ci/config/vm_centos.yml
