stages:
  - build_deps
  - build
  - unit_tests_cpp
  - unit_tests_python
  - integration_tests
  - unit_tests_python_nightly
  - integration_tests_nightly

variables:
  GIT_STRATEGY: fetch
  CACHE_DIR: cache/gaspicxx
  TNT_CI_DIR: ${CI_PROJECT_DIR}/meta/ci
  TNT_INSTALL_DIR: ${CI_PROJECT_DIR}/install
  TNT_BUILD_DIR: ${CI_PROJECT_DIR}/build
  TNT_LD_LIBRARY_PATH: ${CI_PROJECT_DIR}/build
  GASPICXX_DIR: tmp/gaspicxx
  GASPICXX_SHA1: 78c3ec2b11e2825a5d5bff0d1ed4ef3560dc9c7a # explicitely set the commit SHA1 (default: master)
  RUNNER_HOME: /home/gitlab-runner

include: 
  - local: meta/ci/config/common.yml
  - local: meta/ci/config/dependencies.yml
  - local: meta/ci/config/tnt_cluster.yml
  - local: meta/ci/config/vm_centos.yml

cache:
